/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pair.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Registration service. Represents a row in the &quot;Acme_Registration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.pair.registration.model.impl.RegistrationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.pair.registration.model.impl.RegistrationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Registration
 * @generated
 */
@ProviderType
public interface RegistrationModel
	extends BaseModel<Registration>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration model instance should use the {@link Registration} interface instead.
	 */

	/**
	 * Returns the primary key of this registration.
	 *
	 * @return the primary key of this registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration.
	 *
	 * @param primaryKey the primary key of this registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration ID of this registration.
	 *
	 * @return the registration ID of this registration
	 */
	public long getRegistrationId();

	/**
	 * Sets the registration ID of this registration.
	 *
	 * @param registrationId the registration ID of this registration
	 */
	public void setRegistrationId(long registrationId);

	/**
	 * Returns the group ID of this registration.
	 *
	 * @return the group ID of this registration
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this registration.
	 *
	 * @param groupId the group ID of this registration
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this registration.
	 *
	 * @return the user ID of this registration
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this registration.
	 *
	 * @param userId the user ID of this registration
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this registration.
	 *
	 * @return the user uuid of this registration
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this registration.
	 *
	 * @param userUuid the user uuid of this registration
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this registration.
	 *
	 * @return the company ID of this registration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this registration.
	 *
	 * @param companyId the company ID of this registration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this registration.
	 *
	 * @return the create date of this registration
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this registration.
	 *
	 * @param createDate the create date of this registration
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this registration.
	 *
	 * @return the modified date of this registration
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this registration.
	 *
	 * @param modifiedDate the modified date of this registration
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this registration.
	 *
	 * @return the first name of this registration
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this registration.
	 *
	 * @param firstName the first name of this registration
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this registration.
	 *
	 * @return the last name of this registration
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this registration.
	 *
	 * @param lastName the last name of this registration
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email address of this registration.
	 *
	 * @return the email address of this registration
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this registration.
	 *
	 * @param emailAddress the email address of this registration
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the username of this registration.
	 *
	 * @return the username of this registration
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this registration.
	 *
	 * @param username the username of this registration
	 */
	public void setUsername(String username);

	/**
	 * Returns the male of this registration.
	 *
	 * @return the male of this registration
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this registration is male.
	 *
	 * @return <code>true</code> if this registration is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this registration is male.
	 *
	 * @param male the male of this registration
	 */
	public void setMale(boolean male);

	/**
	 * Returns the birthday of this registration.
	 *
	 * @return the birthday of this registration
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this registration.
	 *
	 * @param birthday the birthday of this registration
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the password of this registration.
	 *
	 * @return the password of this registration
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this registration.
	 *
	 * @param password the password of this registration
	 */
	public void setPassword(String password);

	/**
	 * Returns the confirm password of this registration.
	 *
	 * @return the confirm password of this registration
	 */
	@AutoEscape
	public String getConfirmPassword();

	/**
	 * Sets the confirm password of this registration.
	 *
	 * @param confirmPassword the confirm password of this registration
	 */
	public void setConfirmPassword(String confirmPassword);

	/**
	 * Returns the home phone of this registration.
	 *
	 * @return the home phone of this registration
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this registration.
	 *
	 * @param homePhone the home phone of this registration
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this registration.
	 *
	 * @return the mobile phone of this registration
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this registration.
	 *
	 * @param mobilePhone the mobile phone of this registration
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the address1 of this registration.
	 *
	 * @return the address1 of this registration
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this registration.
	 *
	 * @param address1 the address1 of this registration
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this registration.
	 *
	 * @return the address2 of this registration
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this registration.
	 *
	 * @param address2 the address2 of this registration
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this registration.
	 *
	 * @return the city of this registration
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this registration.
	 *
	 * @param city the city of this registration
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this registration.
	 *
	 * @return the state of this registration
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this registration.
	 *
	 * @param state the state of this registration
	 */
	public void setState(String state);

	/**
	 * Returns the zipcode of this registration.
	 *
	 * @return the zipcode of this registration
	 */
	@AutoEscape
	public String getZipcode();

	/**
	 * Sets the zipcode of this registration.
	 *
	 * @param zipcode the zipcode of this registration
	 */
	public void setZipcode(String zipcode);

	/**
	 * Returns the security question of this registration.
	 *
	 * @return the security question of this registration
	 */
	@AutoEscape
	public String getSecurityQuestion();

	/**
	 * Sets the security question of this registration.
	 *
	 * @param securityQuestion the security question of this registration
	 */
	public void setSecurityQuestion(String securityQuestion);

	/**
	 * Returns the answer of this registration.
	 *
	 * @return the answer of this registration
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this registration.
	 *
	 * @param answer the answer of this registration
	 */
	public void setAnswer(String answer);

	/**
	 * Returns the accepted to u of this registration.
	 *
	 * @return the accepted to u of this registration
	 */
	public boolean getAcceptedToU();

	/**
	 * Returns <code>true</code> if this registration is accepted to u.
	 *
	 * @return <code>true</code> if this registration is accepted to u; <code>false</code> otherwise
	 */
	public boolean isAcceptedToU();

	/**
	 * Sets whether this registration is accepted to u.
	 *
	 * @param acceptedToU the accepted to u of this registration
	 */
	public void setAcceptedToU(boolean acceptedToU);

}