/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pair.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RegistrationTrack service. Represents a row in the &quot;Acme_RegistrationTrack&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.pair.registration.model.impl.RegistrationTrackModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.pair.registration.model.impl.RegistrationTrackImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationTrack
 * @generated
 */
@ProviderType
public interface RegistrationTrackModel
	extends BaseModel<RegistrationTrack>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration track model instance should use the {@link RegistrationTrack} interface instead.
	 */

	/**
	 * Returns the primary key of this registration track.
	 *
	 * @return the primary key of this registration track
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration track.
	 *
	 * @param primaryKey the primary key of this registration track
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration track ID of this registration track.
	 *
	 * @return the registration track ID of this registration track
	 */
	public long getRegistrationTrackId();

	/**
	 * Sets the registration track ID of this registration track.
	 *
	 * @param registrationTrackId the registration track ID of this registration track
	 */
	public void setRegistrationTrackId(long registrationTrackId);

	/**
	 * Returns the group ID of this registration track.
	 *
	 * @return the group ID of this registration track
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this registration track.
	 *
	 * @param groupId the group ID of this registration track
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this registration track.
	 *
	 * @return the user ID of this registration track
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this registration track.
	 *
	 * @param userId the user ID of this registration track
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this registration track.
	 *
	 * @return the user uuid of this registration track
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this registration track.
	 *
	 * @param userUuid the user uuid of this registration track
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this registration track.
	 *
	 * @return the company ID of this registration track
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this registration track.
	 *
	 * @param companyId the company ID of this registration track
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this registration track.
	 *
	 * @return the create date of this registration track
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this registration track.
	 *
	 * @param createDate the create date of this registration track
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this registration track.
	 *
	 * @return the modified date of this registration track
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this registration track.
	 *
	 * @param modifiedDate the modified date of this registration track
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the event datetime of this registration track.
	 *
	 * @return the event datetime of this registration track
	 */
	public Date getEventDatetime();

	/**
	 * Sets the event datetime of this registration track.
	 *
	 * @param eventDatetime the event datetime of this registration track
	 */
	public void setEventDatetime(Date eventDatetime);

	/**
	 * Returns the screen name of this registration track.
	 *
	 * @return the screen name of this registration track
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this registration track.
	 *
	 * @param screenName the screen name of this registration track
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the i p adress of this registration track.
	 *
	 * @return the i p adress of this registration track
	 */
	@AutoEscape
	public String getIPAdress();

	/**
	 * Sets the i p adress of this registration track.
	 *
	 * @param iPAdress the i p adress of this registration track
	 */
	public void setIPAdress(String iPAdress);

	/**
	 * Returns the event type of this registration track.
	 *
	 * @return the event type of this registration track
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this registration track.
	 *
	 * @param eventType the event type of this registration track
	 */
	public void setEventType(String eventType);

}