<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.liferay</groupId>
  <artifactId>com.liferay.gradle.plugins.defaults</artifactId>
  <version>7.0.219</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>com.github.jk1</groupId>
      <artifactId>gradle-license-report</artifactId>
      <version>1.8</version>
    </dependency>
    <dependency>
      <groupId>com.gradle.publish</groupId>
      <artifactId>plugin-publish-plugin</artifactId>
      <version>0.11.0</version>
    </dependency>
    <dependency>
      <groupId>com.netflix.nebula</groupId>
      <artifactId>gradle-extra-configurations-plugin</artifactId>
      <version>3.1.0</version>
    </dependency>
    <dependency>
      <groupId>gradle.plugin.com.github.maiflai</groupId>
      <artifactId>gradle-scalatest</artifactId>
      <version>0.25</version>
    </dependency>
    <dependency>
      <groupId>gradle.plugin.com.github.spotbugs.snom</groupId>
      <artifactId>spotbugs-gradle-plugin</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.aries.jmx</groupId>
      <artifactId>org.apache.aries.jmx.api</artifactId>
      <version>1.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-gradle-plugin</artifactId>
      <version>2.4.1</version>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <id>apache</id>
      <name>Apache</name>
      <url>https://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>liferay-public</id>
      <name>Liferay Public</name>
      <url>https://repository-cdn.liferay.com/nexus/content/repositories/public</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>jaspersoft-third-party</id>
      <name>Jaspersoft Third-Party</name>
      <url>http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts</url>
      <layout>default</layout>
    </repository>
  </repositories>
</project>