/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pair.registration.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.pair.registration.model.RegistrationTrack;
import com.liferay.pair.registration.model.RegistrationTrackModel;
import com.liferay.pair.registration.model.RegistrationTrackSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RegistrationTrack service. Represents a row in the &quot;Acme_RegistrationTrack&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RegistrationTrackModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationTrackImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationTrackImpl
 * @generated
 */
@JSON(strict = true)
public class RegistrationTrackModelImpl
	extends BaseModelImpl<RegistrationTrack> implements RegistrationTrackModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration track model instance should use the <code>RegistrationTrack</code> interface instead.
	 */
	public static final String TABLE_NAME = "Acme_RegistrationTrack";

	public static final Object[][] TABLE_COLUMNS = {
		{"registrationTrackId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"eventDatetime", Types.TIMESTAMP}, {"screenName", Types.VARCHAR},
		{"iPAdress", Types.VARCHAR}, {"eventType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("registrationTrackId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("eventDatetime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("screenName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("iPAdress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Acme_RegistrationTrack (registrationTrackId LONG not null primary key,groupId LONG,userId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,eventDatetime DATE null,screenName VARCHAR(75) null,iPAdress VARCHAR(75) null,eventType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Acme_RegistrationTrack";

	public static final String ORDER_BY_JPQL =
		" ORDER BY registrationTrack.registrationTrackId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Acme_RegistrationTrack.registrationTrackId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTRATIONTRACKID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RegistrationTrack toModel(RegistrationTrackSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RegistrationTrack model = new RegistrationTrackImpl();

		model.setRegistrationTrackId(soapModel.getRegistrationTrackId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEventDatetime(soapModel.getEventDatetime());
		model.setScreenName(soapModel.getScreenName());
		model.setIPAdress(soapModel.getIPAdress());
		model.setEventType(soapModel.getEventType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RegistrationTrack> toModels(
		RegistrationTrackSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RegistrationTrack> models = new ArrayList<RegistrationTrack>(
			soapModels.length);

		for (RegistrationTrackSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public RegistrationTrackModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _registrationTrackId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRegistrationTrackId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _registrationTrackId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RegistrationTrack.class;
	}

	@Override
	public String getModelClassName() {
		return RegistrationTrack.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RegistrationTrack, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RegistrationTrack, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationTrack, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RegistrationTrack)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RegistrationTrack, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RegistrationTrack, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RegistrationTrack)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RegistrationTrack, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RegistrationTrack, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RegistrationTrack>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RegistrationTrack.class.getClassLoader(), RegistrationTrack.class,
			ModelWrapper.class);

		try {
			Constructor<RegistrationTrack> constructor =
				(Constructor<RegistrationTrack>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<RegistrationTrack, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RegistrationTrack, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RegistrationTrack, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RegistrationTrack, Object>>();
		Map<String, BiConsumer<RegistrationTrack, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<RegistrationTrack, ?>>();

		attributeGetterFunctions.put(
			"registrationTrackId", RegistrationTrack::getRegistrationTrackId);
		attributeSetterBiConsumers.put(
			"registrationTrackId",
			(BiConsumer<RegistrationTrack, Long>)
				RegistrationTrack::setRegistrationTrackId);
		attributeGetterFunctions.put("groupId", RegistrationTrack::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<RegistrationTrack, Long>)RegistrationTrack::setGroupId);
		attributeGetterFunctions.put("userId", RegistrationTrack::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<RegistrationTrack, Long>)RegistrationTrack::setUserId);
		attributeGetterFunctions.put(
			"companyId", RegistrationTrack::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<RegistrationTrack, Long>)
				RegistrationTrack::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", RegistrationTrack::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<RegistrationTrack, Date>)
				RegistrationTrack::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", RegistrationTrack::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<RegistrationTrack, Date>)
				RegistrationTrack::setModifiedDate);
		attributeGetterFunctions.put(
			"eventDatetime", RegistrationTrack::getEventDatetime);
		attributeSetterBiConsumers.put(
			"eventDatetime",
			(BiConsumer<RegistrationTrack, Date>)
				RegistrationTrack::setEventDatetime);
		attributeGetterFunctions.put(
			"screenName", RegistrationTrack::getScreenName);
		attributeSetterBiConsumers.put(
			"screenName",
			(BiConsumer<RegistrationTrack, String>)
				RegistrationTrack::setScreenName);
		attributeGetterFunctions.put(
			"iPAdress", RegistrationTrack::getIPAdress);
		attributeSetterBiConsumers.put(
			"iPAdress",
			(BiConsumer<RegistrationTrack, String>)
				RegistrationTrack::setIPAdress);
		attributeGetterFunctions.put(
			"eventType", RegistrationTrack::getEventType);
		attributeSetterBiConsumers.put(
			"eventType",
			(BiConsumer<RegistrationTrack, String>)
				RegistrationTrack::setEventType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getRegistrationTrackId() {
		return _registrationTrackId;
	}

	@Override
	public void setRegistrationTrackId(long registrationTrackId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationTrackId = registrationTrackId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getEventDatetime() {
		return _eventDatetime;
	}

	@Override
	public void setEventDatetime(Date eventDatetime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventDatetime = eventDatetime;
	}

	@JSON
	@Override
	public String getScreenName() {
		if (_screenName == null) {
			return "";
		}
		else {
			return _screenName;
		}
	}

	@Override
	public void setScreenName(String screenName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_screenName = screenName;
	}

	@JSON
	@Override
	public String getIPAdress() {
		if (_iPAdress == null) {
			return "";
		}
		else {
			return _iPAdress;
		}
	}

	@Override
	public void setIPAdress(String iPAdress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iPAdress = iPAdress;
	}

	@JSON
	@Override
	public String getEventType() {
		if (_eventType == null) {
			return "";
		}
		else {
			return _eventType;
		}
	}

	@Override
	public void setEventType(String eventType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventType = eventType;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RegistrationTrack.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RegistrationTrack toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RegistrationTrack>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RegistrationTrackImpl registrationTrackImpl =
			new RegistrationTrackImpl();

		registrationTrackImpl.setRegistrationTrackId(getRegistrationTrackId());
		registrationTrackImpl.setGroupId(getGroupId());
		registrationTrackImpl.setUserId(getUserId());
		registrationTrackImpl.setCompanyId(getCompanyId());
		registrationTrackImpl.setCreateDate(getCreateDate());
		registrationTrackImpl.setModifiedDate(getModifiedDate());
		registrationTrackImpl.setEventDatetime(getEventDatetime());
		registrationTrackImpl.setScreenName(getScreenName());
		registrationTrackImpl.setIPAdress(getIPAdress());
		registrationTrackImpl.setEventType(getEventType());

		registrationTrackImpl.resetOriginalValues();

		return registrationTrackImpl;
	}

	@Override
	public int compareTo(RegistrationTrack registrationTrack) {
		long primaryKey = registrationTrack.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RegistrationTrack)) {
			return false;
		}

		RegistrationTrack registrationTrack = (RegistrationTrack)object;

		long primaryKey = registrationTrack.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RegistrationTrack> toCacheModel() {
		RegistrationTrackCacheModel registrationTrackCacheModel =
			new RegistrationTrackCacheModel();

		registrationTrackCacheModel.registrationTrackId =
			getRegistrationTrackId();

		registrationTrackCacheModel.groupId = getGroupId();

		registrationTrackCacheModel.userId = getUserId();

		registrationTrackCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			registrationTrackCacheModel.createDate = createDate.getTime();
		}
		else {
			registrationTrackCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			registrationTrackCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			registrationTrackCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date eventDatetime = getEventDatetime();

		if (eventDatetime != null) {
			registrationTrackCacheModel.eventDatetime = eventDatetime.getTime();
		}
		else {
			registrationTrackCacheModel.eventDatetime = Long.MIN_VALUE;
		}

		registrationTrackCacheModel.screenName = getScreenName();

		String screenName = registrationTrackCacheModel.screenName;

		if ((screenName != null) && (screenName.length() == 0)) {
			registrationTrackCacheModel.screenName = null;
		}

		registrationTrackCacheModel.iPAdress = getIPAdress();

		String iPAdress = registrationTrackCacheModel.iPAdress;

		if ((iPAdress != null) && (iPAdress.length() == 0)) {
			registrationTrackCacheModel.iPAdress = null;
		}

		registrationTrackCacheModel.eventType = getEventType();

		String eventType = registrationTrackCacheModel.eventType;

		if ((eventType != null) && (eventType.length() == 0)) {
			registrationTrackCacheModel.eventType = null;
		}

		return registrationTrackCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RegistrationTrack, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RegistrationTrack, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationTrack, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RegistrationTrack)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RegistrationTrack, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RegistrationTrack, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationTrack, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RegistrationTrack)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RegistrationTrack>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _registrationTrackId;
	private long _groupId;
	private long _userId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _eventDatetime;
	private String _screenName;
	private String _iPAdress;
	private String _eventType;

	public <T> T getColumnValue(String columnName) {
		Function<RegistrationTrack, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RegistrationTrack)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("registrationTrackId", _registrationTrackId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("eventDatetime", _eventDatetime);
		_columnOriginalValues.put("screenName", _screenName);
		_columnOriginalValues.put("iPAdress", _iPAdress);
		_columnOriginalValues.put("eventType", _eventType);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("registrationTrackId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("eventDatetime", 64L);

		columnBitmasks.put("screenName", 128L);

		columnBitmasks.put("iPAdress", 256L);

		columnBitmasks.put("eventType", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	@Override
	public RegistrationTrack cloneWithOriginalValues(){
		return null;
	}

	private long _columnBitmask;
	private RegistrationTrack _escapedModel;

}